"use client";

// import './globals.css'
import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import {ThemeProvider} from "@mui/material";
import {createTheme} from '@mui/material/styles';
import Link from "next/link";

const inter = Inter({subsets: ['latin']})

const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}
let theme = createTheme({
    palette: {
        primary: {
            main: '#0052cc',
        },
        secondary: {
            main: '#edf2ff',
        },
    },
});

const darkTheme = createTheme({
    palette: {
        mode: 'dark',
    },
});

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <body className={inter.className} style={{background:'white'}}>
        <ThemeProvider theme={theme}>
            <h1>Template management</h1>
            <Link href='/templates'>Templates</Link>
            &nbsp;&nbsp;&nbsp;
            <Link href='/categories'>Categories</Link>
            <hr/>
            <br/>
            <br/>
            {children}
        </ThemeProvider>
        </body>

        </html>
    )
}
